# lang
language: node_js

# nodejs version
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "travis"
  - git config user.email "she.ct@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - develop

env:
  global:
  - GH_REF: github.com/spaco/spaco.github.io
